### ISSUE TITLE
Drupal v8.2.5 - Symfony/Yaml wasn't found

### ISSUE THREAD

**Issue by ronpearl** [ahebrank/fontawesome_field#1]
This is our first round at messing with Drupal 8, but using v8.2.5 with your module failed when trying to access the Yaml component from Symfony. In your .module file I had to change Line 9 to:  

use Symfony\Component\Yaml\Yaml;

Not sure if this was changed with the newest version, but once I did that it seems to work fine thus far.  BTW, thanks for this module!

**Comment by ahebrank** [comment]
Thanks, it was a change I ported over from the 7.x branch, just guessed the namespace without testing (fontawesome includes a yaml file in their repo that groups all the icons, so the change is to read that in and use it rather than rolling our own PHP array).

I'll update now.
